import jsPDF from 'jspdf';
import 'jspdf-autotable';
import {
    calculateOverallScore,
    calculateExternalScore,
    calculateInternalScore,
    getScoreInterpretation,
    getAllCriticalActionItems
} from './biosecurityScoring';
import { getAllFocusAreas } from '../data/questions_data';

/**
 * Generate PDF report for biosecurity assessment
 * @param {object} assessment - Current assessment data
 * @param {object} farmProfile - Farm profile data
 * @param {string} language - Current language (en/id/vt)
 * @returns {jsPDF} - PDF document
 */
export function generateBiosecurityReport(assessment, farmProfile, language = 'en') {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    // Translations
    const translations = {
        en: {
            title: 'Biosecurity Assessment Report',
            subtitle: 'FarmWell - PigWell',
            farmInfo: 'Farm Information',
            assessmentDate: 'Assessment Date',
            overallScore: 'Overall Biosecurity Score',
            externalBiosecurity: 'External Biosecurity',
            internalBiosecurity: 'Internal Biosecurity',
            focusAreaScores: 'Focus Area Scores',
            criticalActions: 'Critical Action Items',
            recommendations: 'These areas scored below 50 and require immediate attention',
            noCriticalItems: 'Great! No critical action items found.',
            generatedBy: 'Generated by FarmWell - PigWell',
            page: 'Page'
        },
        id: {
            title: 'Laporan Penilaian Biosekuriti',
            subtitle: 'FarmWell - PigWell',
            farmInfo: 'Informasi Peternakan',
            assessmentDate: 'Tanggal Penilaian',
            overallScore: 'Skor Biosekuriti Keseluruhan',
            externalBiosecurity: 'Biosekuriti Eksternal',
            internalBiosecurity: 'Biosekuriti Internal',
            focusAreaScores: 'Skor Area Fokus',
            criticalActions: 'Item Tindakan Kritis',
            recommendations: 'Area ini mendapat skor di bawah 50 dan memerlukan perhatian segera',
            noCriticalItems: 'Bagus! Tidak ada item tindakan kritis.',
            generatedBy: 'Dibuat oleh FarmWell - PigWell',
            page: 'Halaman'
        },
        vt: {
            title: 'Báo cáo Đánh giá An ninh sinh học',
            subtitle: 'FarmWell - PigWell',
            farmInfo: 'Thông tin Trang trại',
            assessmentDate: 'Ngày Đánh giá',
            overallScore: 'Điểm An ninh sinh học Tổng thể',
            externalBiosecurity: 'An ninh sinh học Bên ngoài',
            internalBiosecurity: 'An ninh sinh học Bên trong',
            focusAreaScores: 'Điểm Khu vực Trọng tâm',
            criticalActions: 'Mục Hành động Quan trọng',
            recommendations: 'Các khu vực này có điểm dưới 50 và cần chú ý ngay',
            noCriticalItems: 'Tuyệt vời! Không có mục hành động quan trọng nào.',
            generatedBy: 'Được tạo bởi FarmWell - PigWell',
            page: 'Trang'
        }
    };

    const t = translations[language] || translations.en;

    // Calculate scores
    const overallScore = calculateOverallScore(assessment, language);
    const externalScore = calculateExternalScore(assessment, language);
    const internalScore = calculateInternalScore(assessment, language);
    const interpretation = getScoreInterpretation(overallScore, language);
    const criticalItems = getAllCriticalActionItems(assessment, language);
    const focusAreas = getAllFocusAreas(language);

    // Header
    doc.setFillColor(41, 128, 185);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(t.title, pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(t.subtitle, pageWidth / 2, 30, { align: 'center' });

    yPosition = 50;

    // Farm Information
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(t.farmInfo, 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`${t.assessmentDate}: ${new Date(assessment.started_at).toLocaleDateString()}`, 20, yPosition);
    yPosition += 20;

    // Overall Score Box
    const scoreColor = getScoreColor(overallScore);
    doc.setFillColor(...scoreColor);
    doc.roundedRect(20, yPosition, pageWidth - 40, 40, 3, 3, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text(t.overallScore, pageWidth / 2, yPosition + 12, { align: 'center' });

    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(overallScore.toString(), pageWidth / 2, yPosition + 25, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(interpretation.label, pageWidth / 2, yPosition + 35, { align: 'center' });

    yPosition += 50;

    // External and Internal Scores
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');

    const boxWidth = (pageWidth - 50) / 2;

    // External Score
    doc.setDrawColor(41, 128, 185);
    doc.setLineWidth(0.5);
    doc.rect(20, yPosition, boxWidth, 30);
    doc.text(t.externalBiosecurity, 25, yPosition + 10);
    doc.setFontSize(18);
    doc.text(externalScore.toString(), 25, yPosition + 23);

    // Internal Score
    doc.setFontSize(11);
    doc.text(t.internalBiosecurity, 30 + boxWidth, yPosition + 10);
    doc.setFontSize(18);
    doc.text(internalScore.toString(), 30 + boxWidth, yPosition + 23);
    doc.rect(30 + boxWidth, yPosition, boxWidth, 30);

    yPosition += 45;

    // Focus Area Scores Table
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(t.focusAreaScores, 20, yPosition);
    yPosition += 5;

    const focusAreaData = focusAreas.map(fa => {
        const faData = assessment.focus_areas[fa.number];
        const score = faData?.score || 0;
        return [
            `${language === 'en' ? 'Focus Area' : language === 'id' ? 'Area Fokus' : 'Khu vực'} ${fa.number}`,
            fa.name,
            score.toString()
        ];
    });

    doc.autoTable({
        startY: yPosition,
        head: [[
            language === 'en' ? 'Focus Area' : language === 'id' ? 'Area Fokus' : 'Khu vực',
            language === 'en' ? 'Name' : language === 'id' ? 'Nama' : 'Tên',
            language === 'en' ? 'Score' : language === 'id' ? 'Skor' : 'Điểm'
        ]],
        body: focusAreaData,
        theme: 'striped',
        headStyles: { fillColor: [41, 128, 185] },
        margin: { left: 20, right: 20 }
    });

    yPosition = doc.lastAutoTable.finalY + 15;

    // Critical Action Items
    if (yPosition > pageHeight - 60) {
        doc.addPage();
        yPosition = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(t.criticalActions, 20, yPosition);
    yPosition += 5;

    if (criticalItems.length === 0) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 128, 0);
        doc.text(t.noCriticalItems, 20, yPosition + 10);
    } else {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        doc.text(t.recommendations, 20, yPosition + 5);
        yPosition += 10;

        const criticalData = criticalItems.map(item => [
            `Q${item.questionNumber}`,
            item.question.substring(0, 60) + (item.question.length > 60 ? '...' : ''),
            `${language === 'en' ? 'Focus Area' : language === 'id' ? 'Area' : 'Khu vực'} ${item.focusArea}`,
            item.score.toString()
        ]);

        doc.autoTable({
            startY: yPosition,
            head: [[
                'Q#',
                language === 'en' ? 'Question' : language === 'id' ? 'Pertanyaan' : 'Câu hỏi',
                language === 'en' ? 'Focus Area' : language === 'id' ? 'Area Fokus' : 'Khu vực',
                language === 'en' ? 'Score' : language === 'id' ? 'Skor' : 'Điểm'
            ]],
            body: criticalData,
            theme: 'striped',
            headStyles: { fillColor: [231, 76, 60] },
            margin: { left: 20, right: 20 },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 35 },
                3: { cellWidth: 20 }
            }
        });
    }

    // Footer on all pages
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.setFont('helvetica', 'normal');
        doc.text(
            `${t.generatedBy} | ${t.page} ${i} / ${totalPages}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    return doc;
}

/**
 * Get RGB color based on score
 */
function getScoreColor(score) {
    if (score >= 80) return [16, 185, 129]; // Green
    if (score >= 60) return [59, 130, 246]; // Blue
    if (score >= 40) return [245, 158, 11]; // Orange
    return [239, 68, 68]; // Red
}

/**
 * Download PDF report
 */
export function downloadBiosecurityReport(assessment, farmProfile, language = 'en') {
    const doc = generateBiosecurityReport(assessment, farmProfile, language);
    const filename = `PigWell_Biosecurity_Report_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
}

export default {
    generateBiosecurityReport,
    downloadBiosecurityReport
};
